spring:
  config:
    import: classpath:/application-core.yml

search:
  source:
    kakao:
      host: https://dapi.kakao.com
      path: /v2/search/blog
      api-key: KakaoAK 4c3d679ec3eead40fcb2c1034acff8d4
    naver:
      host: https://openapi.naver.com
      path: /v1/search/blog.json
      client-id: 76zgl1YhduNgdA4zKGQR
      client-secret: u1WlQdXYSX